-- Este projeto foi migrado de PostgreSQL para MongoDB.
-- O schema relacional abaixo não é mais utilizado.
--
-- A estrutura de dados atual é definida pelos schemas Mongoose em:
--   backend/src/models/
--
-- Para popular o usuário administrador padrão, rode:
--   node database/seed.js
--
-- Consulte docs/requisitos.md (seção 4/5) para o modelo de dados atualizado.
